# Generated by Django 3.1.1 on 2020-10-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='main_image',
            field=models.ImageField(default='defaultimage', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='name',
            field=models.CharField(default='defaultname', max_length=50),
        ),
    ]
