# Generated by Django 3.1.1 on 2020-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20201009_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='main_image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='email',
            field=models.CharField(default='default@email.com', max_length=50),
        ),
    ]
