# Generated by Django 3.1.1 on 2020-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20201009_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='repeat_password',
            field=models.CharField(default='defaultrepeatpassword', max_length=20),
        ),
    ]
