# Generated by Django 3.1.1 on 2020-10-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreportmodel',
            old_name='projectDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userreportmodel',
            old_name='projectFeedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='userreportmodel',
            old_name='projectName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userreportmodel',
            old_name='userName',
            new_name='user',
        ),
    ]
