# Generated by Django 3.1.1 on 2020-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
