# Generated by Django 3.1.1 on 2020-10-26 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201026_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
