# Generated by Django 3.1.1 on 2020-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userreportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreportmodel',
            name='date',
            field=models.DateField(max_length=500),
        ),
    ]
