# Generated by Django 3.1.1 on 2020-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201104_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empuser',
            field=models.CharField(max_length=100),
        ),
    ]
