# Generated by Django 3.1.1 on 2020-11-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201104_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empuser',
        ),
    ]
