# Generated by Django 3.1.1 on 2020-10-26 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201026_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportmodel',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
