# Generated by Django 3.1.1 on 2020-11-02 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_userreportmodel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='defaultname', max_length=50)),
                ('profile_image', models.ImageField(default='defaultimage', upload_to='images/')),
                ('password', models.CharField(default='defaultpassword', max_length=20)),
                ('repeat_password', models.CharField(default='defaultrepeatpassword', max_length=20)),
                ('email', models.CharField(default='default@email.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='defaultimage', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
