# Generated by Django 3.1.1 on 2020-11-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_employee_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
