# Generated by Django 3.1.1 on 2020-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_employee_empuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empuser',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
