# Generated by Django 3.1.1 on 2020-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201105_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('date', models.DateField(max_length=500)),
                ('time', models.TimeField()),
            ],
        ),
    ]
