# Generated by Django 3.1.1 on 2020-11-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='defaultimage', null=True, upload_to='images/'),
        ),
    ]
